# This is a basic workflow to help you get started with Actions
name: Update plots

# Controls when the action will run. 
on:
  schedule:
    - cron: 0 0/12 * * *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: covid19

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout covid19 repo
        uses: actions/checkout@v2
        with:
          repository: intelligent-environments-lab/covid19
          token: ${{ secrets.COVID19_PAT }} # `GitHub_PAT` is a secret that contains your PAT
          path: covid19
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: dashboard
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cp -r ./covid19/figures ./dashboard
          
      - name: Push
        continue-on-error: true
        run: |
          cd dashboard
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./figures
          git commit -m "generated"
          git push
          
      
